{
  "name": "gitpod-website",
  "description": "Gitpod.io Website",
  "version": "1.0.0",
  "private": true,
  "keywords": [
    "gatsby"
  ],
  "main": "n/a",
  "scripts": {
    "build": "cp -r src/docs/release-notes/* static/release-notes/ && gatsby build",
    "clean": "rimraf public",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "dev": "gatsby develop",
    "format": "prettier --write \"src/**/*.{ts,tsx,md}\"",
    "lint": "tslint 'src/**/*.{ts,tsx}' -p tsconfig.json",
    "start": "npm run dev",
    "test": "npm run type-check && npm run lint",
    "type-check": "tsc"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "dependencies": {
    "@emotion/core": "10.0.14",
    "@emotion/styled": "10.0.14",
    "babel-plugin-styled-components": "1.10.6",
    "bowser": "2.4.0",
    "classnames": "2.2.6",
    "gatsby": "2.13.25",
    "gatsby-image": "2.2.6",
    "gatsby-plugin-canonical-urls": "2.1.2",
    "gatsby-plugin-catch-links": "2.1.2",
    "gatsby-plugin-emotion": "4.1.2",
    "gatsby-plugin-google-analytics": "2.1.4",
    "gatsby-plugin-react-helmet": "3.1.2",
    "gatsby-plugin-sharp": "2.2.7",
    "gatsby-plugin-sitemap": "2.2.3",
    "gatsby-plugin-typescript": "2.1.2",
    "gatsby-remark-autolink-headers": "2.1.3",
    "gatsby-remark-copy-linked-files": "2.1.3",
    "gatsby-remark-images": "3.1.6",
    "gatsby-remark-prismjs": "3.3.3",
    "gatsby-remark-responsive-iframe": "2.2.4",
    "gatsby-remark-smartypants": "2.1.2",
    "gatsby-source-filesystem": "2.1.5",
    "gatsby-transformer-json": "2.2.2",
    "gatsby-transformer-remark": "2.6.6",
    "gatsby-transformer-sharp": "2.2.3",
    "modern-normalize": "0.5.0",
    "normalize.css": "8.0.1",
    "polished": "3.4.1",
    "prism-themes": "1.1.0",
    "prismjs": "1.16.0",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-helmet": "5.2.1",
    "react-modal-video": "1.2.2",
    "react-tweet-embed": "1.2.2",
    "typescript": "3.5.3"
  },
  "devDependencies": {
    "@types/classnames": "2.2.9",
    "@types/node": "10.14.10",
    "@types/react": "16.8.23",
    "@types/react-dom": "16.8.4",
    "@types/react-helmet": "5.0.8",
    "gh-pages": "2.0.1",
    "prettier": "1.18.2",
    "rimraf": "2.6.3",
    "tslint": "5.18.0",
    "tslint-config-blvd": "1.2.1",
    "tslint-config-prettier": "1.18.0",
    "tslint-plugin-prettier": "2.0.1"
  }
}
